CodeSystem: MindObservationstypCS
Id: mind-observationstyp-cs
Title: "MIND Beobachtungstypen"
Description: "Beobachtungstypen (Observation.code) und zugehörige Komponenten-Codes für MIND-7.1-Beobachtungen."
* ^url = "https://till-ko.github.io/ems-mind-de-r4/CodeSystem/mind-observationstyp-cs"
* ^version = "7.1.0"
* ^status = #active
* ^content = #complete
* ^caseSensitive = true
* #patientenalter "Patientenalter"
* #altersvaliditaet "Altersvalidität"
* #alter-jahre "Alter in Jahren"
* #alter-monate "Alter in Monaten"
* #rd-transport "Rettungsdienstlicher Transport"
* #aerztliche-begleitung "Ärztliche Transportbegleitung"
* #notarzt-nachgefordert "Notarzt nachgefordert"
* #tna-nachgefordert "Tele-Notarzt nachgefordert"
* #kein-transport-mit-patient "Grund für Einsatz ohne Transport trotz Patientenkontakt"
* #kein-transport-ohne-patient "Grund für Einsatz ohne Transport, da kein Patientenkontakt"
* #dokumentierendes-rettungsmittel "Dokumentierendes Rettungsmittel"
* #beteiligte-rettungsmittel "Beteiligte Rettungsmittel"
* #aerztliche-qualifikation "Ärztliche Qualifikation"
* #personalstatus "Status des Personals"
* #symptombeginn-vor-24h "Symptombeginn innerhalb der letzten 24 Stunden"
* #symptombeginn "Zeitpunkt Symptombeginn"
* #symptombeginn-gesichert "Symptombeginn gesichert oder geschätzt"
* #zeit-notfallmeldung "Zeitpunkt Eingang Notfallmeldung"
* #zeit-alarm "Zeitpunkt Alarm"
* #zeit-ausruecken "Zeitpunkt Ausrücken"
* #zeit-ankunft-einsatzort "Zeitpunkt Ankunft Einsatzort"
* #zeit-ankunft-patient "Zeitpunkt Ankunft Patient"
* #zeit-transportbeginn "Zeitpunkt Transportbeginn"
* #zeit-eintreffen-transportziel "Zeitpunkt Eintreffen Transportziel"
* #zeit-uebergabe-patient "Zeitpunkt Übergabe Patient"