CodeSystem: MindMedikamentengabeCS
Id: mind-medikamentengabe-cs
Title: "MIND Medikamentengabe"
Description: "Gültige Kombinationen aus Wirkstoffcode und Applikationsweg gemäß MIND 7.1."
* ^url = "https://till-ko.github.io/ems-mind-de-r4/CodeSystem/mind-medikamentengabe-cs"
* ^version = "7.1.0"
* ^status = #active
* ^experimental = false
* ^publisher = "Till Koch"
* ^content = #complete
* ^caseSensitive = true

* #1001im "Fentanyl - intramuskulär"
* #1001io "Fentanyl - intraossär"
* #1001iv "Fentanyl - intravenös"
* #1001nl "Fentanyl - intranasal"
* #1001sc "Fentanyl - subkutan"
* #1001sl "Fentanyl - sublingual/bukkal"
* #1001td "Fentanyl - transdermal"
* #1002im "Morphin - intramuskulär"
* #1002io "Morphin - intraossär"
* #1002iv "Morphin - intravenös"
* #1002nl "Morphin - intranasal"
* #1002po "Morphin - oral"
* #1002sc "Morphin - subkutan"
* #1002td "Morphin - transdermal"
* #1003im "Piritramid - intramuskulär"
* #1003io "Piritramid - intraossär"
* #1003iv "Piritramid - intravenös"
* #1003sc "Piritramid - subkutan"
* #1004io "Sufentanil - intraossär"
* #1004iv "Sufentanil - intravenös"
* #1004nl "Sufentanil - intranasal"
* #1004sl "Sufentanil - sublingual/bukkal"
* #1005im "anderes Opioid - intramuskulär"
* #1005io "anderes Opioid - intraossär"
* #1005iv "anderes Opioid - intravenös"
* #1005nl "anderes Opioid - intranasal"
* #1005po "anderes Opioid - oral"
* #1005rl "anderes Opioid - rektal"
* #1005sc "anderes Opioid - subkutan"
* #1005sl "anderes Opioid - sublingual/bukkal"
* #1005td "anderes Opioid - transdermal"
* #1006io "Metamizol - intraossär"
* #1006iv "Metamizol - intravenös"
* #1006po "Metamizol - oral"
* #1007io "Paracetamol - intraossär"
* #1007iv "Paracetamol - intravenös"
* #1007po "Paracetamol - oral"
* #1007rl "Paracetamol - rektal"
* #1008io "Oxycodon - intraossär"
* #1008iv "Oxycodon - intravenös"
* #1008po "Oxycodon - oral"
* #1008sc "Oxycodon - subkutan"
* #1008sl "Oxycodon - sublingual/bukkal"
* #1009ih "Ketamin/Esketamin - inhalativ"
* #1009im "Ketamin/Esketamin - intramuskulär"
* #1009io "Ketamin/Esketamin - intraossär"
* #1009iv "Ketamin/Esketamin - intravenös"
* #1009nl "Ketamin/Esketamin - intranasal"
* #1009rl "Ketamin/Esketamin - rektal"
* #1009sc "Ketamin/Esketamin - subkutan"
* #1010io "NSAID - intraossär"
* #1010iv "NSAID - intravenös"
* #1010po "NSAID - oral"
* #1010rl "NSAID - rektal"
* #1011sc "Lokalanästhetikum - subkutan"
* #1011td "Lokalanästhetikum - transdermal"
* #1097xx "vorbehandelt mit Analgetika - sämtliche Applikationsformen"
* #1098ih "sonstiges Analgetikum - inhalativ"
* #1098im "sonstiges Analgetikum - intramuskulär"
* #1098io "sonstiges Analgetikum - intraossär"
* #1098iv "sonstiges Analgetikum - intravenös"
* #1098nl "sonstiges Analgetikum - intranasal"
* #1098po "sonstiges Analgetikum - oral"
* #1098rl "sonstiges Analgetikum - rektal"
* #1098sc "sonstiges Analgetikum - subkutan"
* #1098sl "sonstiges Analgetikum - sublingual/bukkal"
* #1098td "sonstiges Analgetikum - transdermal"
* #1101io "Betablocker - intraossär"
* #1101iv "Betablocker - intravenös"
* #1101po "Betablocker - oral"
* #1102io "Amiodaron - intraossär"
* #1102iv "Amiodaron - intravenös"
* #1102po "Amiodaron - oral"
* #1103io "Adenosin - intraossär"
* #1103iv "Adenosin - intravenös"
* #1104io "Atropin - intraossär"
* #1104iv "Atropin - intravenös"
* #1105io "Verapamil - intraossär"
* #1105iv "Verapamil - intravenös"
* #1105po "Verapamil - oral"
* #1106io "Ajmalin - intraossär"
* #1106iv "Ajmalin - intravenös"
* #1107io "Digitalisglykosid - intraossär"
* #1107iv "Digitalisglykosid - intravenös"
* #1108io "Lidocain - intraossär"
* #1108iv "Lidocain - intravenös"
* #1197xx "vorbehandelt mit Antiarrhythmika - sämtliche Applikationsformen"
* #1198ih "sonstiges Antiarrhythmikum - inhalativ"
* #1198im "sonstiges Antiarrhythmikum - intramuskulär"
* #1198io "sonstiges Antiarrhythmikum - intraossär"
* #1198iv "sonstiges Antiarrhythmikum - intravenös"
* #1198nl "sonstiges Antiarrhythmikum - intranasal"
* #1198po "sonstiges Antiarrhythmikum - oral"
* #1198rl "sonstiges Antiarrhythmikum - rektal"
* #1198sc "sonstiges Antiarrhythmikum - subkutan"
* #1198sl "sonstiges Antiarrhythmikum - sublingual/bukkal"
* #1198td "sonstiges Antiarrhythmikum - transdermal"
* #1201io "Flumazenil - intraossär"
* #1201iv "Flumazenil - intravenös"
* #1201nl "Flumazenil - intranasal"
* #1202po "Carbo medicinalis (Kohle) - oral"
* #1203im "Naloxon - intramuskulär"
* #1203io "Naloxon - intraossär"
* #1203iv "Naloxon - intravenös"
* #1203nl "Naloxon - intranasal"
* #1203sc "Naloxon - subkutan"
* #1204io "Physostigmin - intraossär"
* #1204iv "Physostigmin - intravenös"
* #1205io "Atropin (als Antidot) - intraossär"
* #1205iv "Atropin (als Antidot) - intravenös"
* #1206io "Obidoxim - intraossär"
* #1206iv "Obidoxim - intravenös"
* #1207io "Hydroxocobalamin - intraossär"
* #1207iv "Hydroxocobalamin - intravenös"
* #1208io "Natriumthiosulfat - intraossär"
* #1208iv "Natriumthiosulfat - intravenös"
* #1209io "4-Dimethylaminophenol (4-DMAP) - intraossär"
* #1209iv "4-Dimethylaminophenol (4-DMAP) - intravenös"
* #1210iv "Toloniumchlorid (Toluidinblau) - intravenös"
* #1211io "Methylthioniniumchlorid (Methylenblau) - intraossär"
* #1211iv "Methylthioniniumchlorid (Methylenblau) - intravenös"
* #1297xx "vorbehandelt mit Antidota - sämtliche Applikationsformen"
* #1298ih "sonstiges Antidot - inhalativ"
* #1298im "sonstiges Antidot - intramuskulär"
* #1298io "sonstiges Antidot - intraossär"
* #1298iv "sonstiges Antidot - intravenös"
* #1298nl "sonstiges Antidot - intranasal"
* #1298po "sonstiges Antidot - oral"
* #1298rl "sonstiges Antidot - rektal"
* #1298sc "sonstiges Antidot - subkutan"
* #1298sl "sonstiges Antidot - sublingual/bukkal"
* #1298td "sonstiges Antidot - transdermal"
* #1301io "Dimenhydrinat - intraossär"
* #1301iv "Dimenhydrinat - intravenös"
* #1301po "Dimenhydrinat - oral"
* #1301rl "Dimenhydrinat - rektal"
* #1302io "Metoclopramid - intraossär"
* #1302iv "Metoclopramid - intravenös"
* #1302po "Metoclopramid - oral"
* #1303io "5HT3-Antagonist - intraossär"
* #1303iv "5HT3-Antagonist - intravenös"
* #1303po "5HT3-Antagonist - oral"
* #1303rl "5HT3-Antagonist - rektal"
* #1397xx "vorbehandelt mit Antiemetika - sämtliche Applikationsformen"
* #1398ih "sonstiges Antiemetikum - inhalativ"
* #1398im "sonstiges Antiemetikum - intramuskulär"
* #1398io "sonstiges Antiemetikum - intraossär"
* #1398iv "sonstiges Antiemetikum - intravenös"
* #1398nl "sonstiges Antiemetikum - intranasal"
* #1398po "sonstiges Antiemetikum - oral"
* #1398rl "sonstiges Antiemetikum - rektal"
* #1398sc "sonstiges Antiemetikum - subkutan"
* #1398sl "sonstiges Antiemetikum - sublingual/bukkal"
* #1398td "sonstiges Antiemetikum - transdermal"
* #1401io "Clonazepam - intraossär"
* #1401iv "Clonazepam - intravenös"
* #1402im "Diazepam - intramuskulär"
* #1402io "Diazepam - intraossär"
* #1402iv "Diazepam - intravenös"
* #1402nl "Diazepam - intranasal"
* #1402po "Diazepam - oral"
* #1402rl "Diazepam - rektal"
* #1402sc "Diazepam - subkutan"
* #1402sl "Diazepam - sublingual/bukkal"
* #1403im "Lorazepam - intramuskulär"
* #1403io "Lorazepam - intraossär"
* #1403iv "Lorazepam - intravenös"
* #1403nl "Lorazepam - intranasal"
* #1403po "Lorazepam - oral"
* #1403rl "Lorazepam - rektal"
* #1403sc "Lorazepam - subkutan"
* #1403sl "Lorazepam - sublingual/bukkal"
* #1404im "Midazolam - intramuskulär"
* #1404io "Midazolam - intraossär"
* #1404iv "Midazolam - intravenös"
* #1404nl "Midazolam - intranasal"
* #1404po "Midazolam - oral"
* #1404rl "Midazolam - rektal"
* #1404sc "Midazolam - subkutan"
* #1404sl "Midazolam - sublingual/bukkal"
* #1405io "Phenytoin - intraossär"
* #1405iv "Phenytoin - intravenös"
* #1406io "Levetiracetam - intraossär"
* #1406iv "Levetiracetam - intravenös"
* #1497xx "vorbehandelt mit Sedativa/Antiepileptika - sämtliche Applikationsformen"
* #1498ih "sonstiges Sedativum/Antiepileptikum - inhalativ"
* #1498im "sonstiges Sedativum/Antiepileptikum - intramuskulär"
* #1498io "sonstiges Sedativum/Antiepileptikum - intraossär"
* #1498iv "sonstiges Sedativum/Antiepileptikum - intravenös"
* #1498nl "sonstiges Sedativum/Antiepileptikum - intranasal"
* #1498po "sonstiges Sedativum/Antiepileptikum - oral"
* #1498rl "sonstiges Sedativum/Antiepileptikum - rektal"
* #1498sc "sonstiges Sedativum/Antiepileptikum - subkutan"
* #1498sl "sonstiges Sedativum/Antiepileptikum - sublingual/bukkal"
* #1498td "sonstiges Sedativum/Antiepileptikum - transdermal"
* #1501iv "Urapidil - intravenös"
* #1502io "Glyceroltrinitrat - intraossär"
* #1502iv "Glyceroltrinitrat - intravenös"
* #1502sl "Glyceroltrinitrat - sublingual/bukkal"
* #1503io "Clonidin - intraossär"
* #1503iv "Clonidin - intravenös"
* #1503po "Clonidin - oral"
* #1509io "Urapidil - intraossär" 
// TODO: CHECK FOR EMAIL TO DIVI, weather this was an error as the i.o. code doesnt follow the urapidil code in the spec
* #1597xx "vorbehandelt mit Antihypertensiva/Vasodilatantien - sämtliche Applikationsformen"
* #1598ih "sonstiges Antihypertensivum/Vasodilatans - inhalativ"
* #1598im "sonstiges Antihypertensivum/Vasodilatans - intramuskulär"
* #1598io "sonstiges Antihypertensivum/Vasodilatans - intraossär"
* #1598iv "sonstiges Antihypertensivum/Vasodilatans - intravenös"
* #1598nl "sonstiges Antihypertensivum/Vasodilatans - intranasal"
* #1598po "sonstiges Antihypertensivum/Vasodilatans - oral"
* #1598rl "sonstiges Antihypertensivum/Vasodilatans - rektal"
* #1598sc "sonstiges Antihypertensivum/Vasodilatans - subkutan"
* #1598sl "sonstiges Antihypertensivum/Vasodilatans - sublingual/bukkal"
* #1598td "sonstiges Antihypertensivum/Vasodilatans - transdermal"
* #1601ih "Salbutamol - inhalativ"
* #1601io "Salbutamol - intraossär"
* #1601iv "Salbutamol - intravenös"
* #1602ih "Reproterol - inhalativ"
* #1602io "Reproterol - intraossär"
* #1602iv "Reproterol - intravenös"
* #1603ih "Ipratropiumbromid - inhalativ"
* #1603im "Ipratropiumbromid - intramuskulär"
* #1603io "Ipratropiumbromid - intraossär"
* #1603iv "Ipratropiumbromid - intravenös"
* #1603sc "Ipratropiumbromid - subkutan"
* #1604io "Theophyllin - intraossär"
* #1604iv "Theophyllin - intravenös"
* #1604po "Theophyllin - oral"
* #1697xx "vorbehandelt mit Bronchodilatantien - sämtliche Applikationsformen"
* #1698ih "sonstiges Bronchodilatans - inhalativ"
* #1698im "sonstiges Bronchodilatans - intramuskulär"
* #1698io "sonstiges Bronchodilatans - intraossär"
* #1698iv "sonstiges Bronchodilatans - intravenös"
* #1698nl "sonstiges Bronchodilatans - intranasal"
* #1698po "sonstiges Bronchodilatans - oral"
* #1698rl "sonstiges Bronchodilatans - rektal"
* #1698sc "sonstiges Bronchodilatans - subkutan"
* #1698sl "sonstiges Bronchodilatans - sublingual/bukkal"
* #1698td "sonstiges Bronchodilatans - transdermal"
* #1701io "Furosemid - intraossär"
* #1701iv "Furosemid - intravenös"
* #1797xx "vorbehandelt mit Diuretika - sämtliche Applikationsformen"
* #1798ih "sonstiges Diuretikum - inhalativ"
* #1798im "sonstiges Diuretikum - intramuskulär"
* #1798io "sonstiges Diuretikum - intraossär"
* #1798iv "sonstiges Diuretikum - intravenös"
* #1798nl "sonstiges Diuretikum - intranasal"
* #1798po "sonstiges Diuretikum - oral"
* #1798rl "sonstiges Diuretikum - rektal"
* #1798sc "sonstiges Diuretikum - subkutan"
* #1798sl "sonstiges Diuretikum - sublingual/bukkal"
* #1798td "sonstiges Diuretikum - transdermal"
* #1801ih "Epinephrin - inhalativ"
* #1801im "Epinephrin - intramuskulär"
* #1801io "Epinephrin - intraossär"
* #1801iv "Epinephrin - intravenös"
* #1801nl "Epinephrin - intranasal"
* #1801sc "Epinephrin - subkutan"
* #1802io "Norepinephrin - intraossär"
* #1802iv "Norepinephrin - intravenös"
* #1803io "Cafedrin/Theoadrenalin - intraossär"
* #1803iv "Cafedrin/Theoadrenalin - intravenös"
* #1804io "Dobutamin - intraossär"
* #1804iv "Dobutamin - intravenös"
* #1805io "Vasopressin - intraossär"
* #1805iv "Vasopressin - intravenös"
* #1897xx "vorbehandelt mit Katecholaminen - sämtliche Applikationsformen"
* #1898ih "sonstige Katecholamine - inhalativ"
* #1898im "sonstige Katecholamine - intramuskulär"
* #1898io "sonstige Katecholamine - intraossär"
* #1898iv "sonstige Katecholamine - intravenös"
* #1898nl "sonstige Katecholamine - intranasal"
* #1898po "sonstige Katecholamine - oral"
* #1898rl "sonstige Katecholamine - rektal"
* #1898sc "sonstige Katecholamine - subkutan"
* #1898sl "sonstige Katecholamine - sublingual/bukkal"
* #1898td "sonstige Katecholamine - transdermal"
* #1901ih "Dexametason - inhalativ"
* #1901io "Dexametason - intraossär"
* #1901iv "Dexametason - intravenös"
* #1902ih "Methyl-/Prednisolon - inhalativ"
* #1902io "Methyl-/Prednisolon - intraossär"
* #1902iv "Methyl-/Prednisolon - intravenös"
* #1902rl "Methyl-/Prednisolon - rektal"
* #1997xx "vorbehandelt mit Kortikosteroiden - sämtliche Applikationsformen"
* #1998ih "sonstiges Corticoid - inhalativ"
* #1998im "sonstiges Corticoid - intramuskulär"
* #1998io "sonstiges Corticoid - intraossär"
* #1998iv "sonstiges Corticoid - intravenös"
* #1998nl "sonstiges Corticoid - intranasal"
* #1998po "sonstiges Corticoid - oral"
* #1998rl "sonstiges Corticoid - rektal"
* #1998sc "sonstiges Corticoid - subkutan"
* #1998sl "sonstiges Corticoid - sublingual/bukkal"
* #1998td "sonstiges Corticoid - transdermal"
* #2001im "Suxamethonium - intramuskulär"
* #2001io "Suxamethonium - intraossär"
* #2001iv "Suxamethonium - intravenös"
* #2002io "Rocuronium - intraossär"
* #2002iv "Rocuronium - intravenös"
* #2097xx "vorbehandelt mit Muskelrelaxantien - sämtliche Applikationsformen"
* #2098ih "sonstiges Muskelrelaxans - inhalativ"
* #2098im "sonstiges Muskelrelaxans - intramuskulär"
* #2098io "sonstiges Muskelrelaxans - intraossär"
* #2098iv "sonstiges Muskelrelaxans - intravenös"
* #2098nl "sonstiges Muskelrelaxans - intranasal"
* #2098po "sonstiges Muskelrelaxans - oral"
* #2098rl "sonstiges Muskelrelaxans - rektal"
* #2098sc "sonstiges Muskelrelaxans - subkutan"
* #2098sl "sonstiges Muskelrelaxans - sublingual/bukkal"
* #2098td "sonstiges Muskelrelaxans - transdermal"
* #2101io "Etomidat - intraossär"
* #2101iv "Etomidat - intravenös"
* #2102io "Propofol - intraossär"
* #2102iv "Propofol - intravenös"
* #2103io "Thiopental - intraossär"
* #2103iv "Thiopental - intravenös"
* #2197xx "vorbehandelt mit Narkotika - sämtliche Applikationsformen"
* #2198ih "sonstiges Narkotikum - inhalativ"
* #2198im "sonstiges Narkotikum - intramuskulär"
* #2198io "sonstiges Narkotikum - intraossär"
* #2198iv "sonstiges Narkotikum - intravenös"
* #2198nl "sonstiges Narkotikum - intranasal"
* #2198po "sonstiges Narkotikum - oral"
* #2198rl "sonstiges Narkotikum - rektal"
* #2198sc "sonstiges Narkotikum - subkutan"
* #2198sl "sonstiges Narkotikum - sublingual/bukkal"
* #2198td "sonstiges Narkotikum - transdermal"
* #2201im "Haloperidol - intramuskulär"
* #2201io "Haloperidol - intraossär"
* #2201iv "Haloperidol - intravenös"
* #2202im "Promethazin - intramuskulär"
* #2202io "Promethazin - intraossär"
* #2202iv "Promethazin - intravenös"
* #2297xx "vorbehandelt mit Psychopharmaka - sämtliche Applikationsformen"
* #2298ih "sonstige Psychopharmaka - inhalativ"
* #2298im "sonstige Psychopharmaka - intramuskulär"
* #2298io "sonstige Psychopharmaka - intraossär"
* #2298iv "sonstige Psychopharmaka - intravenös"
* #2298nl "sonstige Psychopharmaka - intranasal"
* #2298po "sonstige Psychopharmaka - oral"
* #2298rl "sonstige Psychopharmaka - rektal"
* #2298sc "sonstige Psychopharmaka - subkutan"
* #2298sl "sonstige Psychopharmaka - sublingual/bukkal"
* #2298td "sonstige Psychopharmaka - transdermal"
* #2301io "UF Heparin - intraossär"
* #2301iv "UF Heparin - intravenös"
* #2301sc "UF Heparin - subkutan"
* #2302sc "NM Heparin - subkutan"
* #2397xx "vorbehandelt mit Antikoagulanzien - sämtliche Applikationsformen"
* #2398im "sonstige Antikoagulanzien - intramuskulär"
* #2398io "sonstige Antikoagulanzien - intraossär"
* #2398iv "sonstige Antikoagulanzien - intravenös"
* #2398po "sonstige Antikoagulanzien - oral"
* #2398sc "sonstige Antikoagulanzien - subkutan"
* #2401io "Acetylsalicylsäure - intraossär"
* #2401iv "Acetylsalicylsäure - intravenös"
* #2401po "Acetylsalicylsäure - oral"
* #2402io "Clopidogrel o. a. - intraossär"
* #2402iv "Clopidogrel o. a. - intravenös"
* #2402po "Clopidogrel o. a. - oral"
* #2497xx "vorbehandelt mit Thrombozytenaggregationshemmern - sämtliche Applikationsformen"
* #2498im "sonstige Thrombozytenaggregationshemmer - intramuskulär"
* #2498io "sonstige Thrombozytenaggregationshemmer - intraossär"
* #2498iv "sonstige Thrombozytenaggregationshemmer - intravenös"
* #2498po "sonstige Thrombozytenaggregationshemmer - oral"
* #2498sc "sonstige Thrombozytenaggregationshemmer - subkutan"
* #2498sl "sonstige Thrombozytenaggregationshemmer - sublingual/bukkal"
* #2501io "Glukose - intraossär"
* #2501iv "Glukose - intravenös"
* #2501po "Glukose - oral"
* #2502io "H1-Blocker - intraossär"
* #2502iv "H1-Blocker - intravenös"
* #2502po "H1-Blocker - oral"
* #2503io "H2-Blocker - intraossär"
* #2503iv "H2-Blocker - intravenös"
* #2503po "H2-Blocker - oral"
* #2504io "Butylscopolamin - intraossär"
* #2504iv "Butylscopolamin - intravenös"
* #2504po "Butylscopolamin - oral"
* #2505io "Antibiotikum - intraossär"
* #2505iv "Antibiotikum - intravenös"
* #2505po "Antibiotikum - oral"
* #2506io "Biperiden - intraossär"
* #2506iv "Biperiden - intravenös"
* #2506po "Biperiden - oral"
* #2507io "Oxytocin - intraossär"
* #2507iv "Oxytocin - intravenös"
* #2507nl "Oxytocin - intranasal"
* #2508ih "Fenoterol (als Tokolytikum) - inhalativ"
* #2508io "Fenoterol (als Tokolytikum) - intraossär"
* #2508iv "Fenoterol (als Tokolytikum) - intravenös"
* #2509io "Kaliumchlorid - intraossär"
* #2509iv "Kaliumchlorid - intravenös"
* #2509po "Kaliumchlorid - oral"
* #2510io "Calciumgluconat - intraossär"
* #2510iv "Calciumgluconat - intravenös"
* #2510td "Calciumgluconat - transdermal"
* #2511io "Magnesiumsulfat - intraossär"
* #2511iv "Magnesiumsulfat - intravenös"
* #2512io "Insulin - intraossär"
* #2512iv "Insulin - intravenös"
* #2512sc "Insulin - subkutan"
* #2513io "Tranexamsäure - intraossär"
* #2513iv "Tranexamsäure - intravenös"
* #2513nl "Tranexamsäure - intranasal"
* #2514io "Natriumhydrogencarbonat - intraossär"
* #2514iv "Natriumhydrogencarbonat - intravenös"
* #2515io "Erythrozytenkonzentrat - intraossär"
* #2515iv "Erythrozytenkonzentrat - intravenös"
* #2516io "FFP - intraossär"
* #2516iv "FFP - intravenös"
* #2517io "PPSB - intraossär"
* #2517iv "PPSB - intravenös"
* #2518io "Fibrinogen - intraossär"
* #2518iv "Fibrinogen - intravenös"
* #2519io "Lyoplasma - intraossär"
* #2519iv "Lyoplasma - intravenös"
* #2520io "Thiamin - intraossär"
* #2520iv "Thiamin - intravenös"
* #2521po "Simeticon - oral"
* #2522nl "abschwellende Nasentropfen - intranasal"
* #2597xx "vorbehandelt mit sonstigen Medikamenten - sämtliche Applikationsformen"
* #2598ih "sonstige Medikamente - inhalativ"
* #2598im "sonstige Medikamente - intramuskulär"
* #2598io "sonstige Medikamente - intraossär"
* #2598iv "sonstige Medikamente - intravenös"
* #2598nl "sonstige Medikamente - intranasal"
* #2598po "sonstige Medikamente - oral"
* #2598rl "sonstige Medikamente - rektal"
* #2598sc "sonstige Medikamente - subkutan"
* #2598sl "sonstige Medikamente - sublingual/bukkal"
* #2598td "sonstige Medikamente - transdermal"
* #2601io "MIND Medikamentencode 2601 - intraossär"
* #2601iv "MIND Medikamentencode 2601 - intravenös"
* #2602io "MIND Medikamentencode 2602 - intraossär"
* #2602iv "MIND Medikamentencode 2602 - intravenös"
* #2603io "MIND Medikamentencode 2603 - intraossär"
* #2603iv "MIND Medikamentencode 2603 - intravenös"
* #2697xx "MIND Medikamentencode 2697 - sämtliche Applikationsformen"
* #2698im "MIND Medikamentencode 2698 - intramuskulär"
* #2698io "MIND Medikamentencode 2698 - intraossär"
* #2698iv "MIND Medikamentencode 2698 - intravenös"
* #2698sc "MIND Medikamentencode 2698 - subkutan"
* #3001io "isotone Kochsalzlösung - intraossär"
* #3001iv "isotone Kochsalzlösung - intravenös"
* #3001sc "isotone Kochsalzlösung - subkutan"
* #3002io "Vollelektrolytlösung - intraossär"
* #3002iv "Vollelektrolytlösung - intravenös"
* #3002sc "Vollelektrolytlösung - subkutan"
* #3097xx "vorbehandelt mit Kristalloid - sämtliche Applikationsformen"
* #3098io "sonstiges Kristalloid - intraossär"
* #3098iv "sonstiges Kristalloid - intravenös"
* #3098sc "sonstiges Kristalloid - subkutan"
* #3101io "HÄS - intraossär"
* #3101iv "HÄS - intravenös"
* #3102io "SVR/Hyperosmol. NaCl - intraossär"
* #3102iv "SVR/Hyperosmol. NaCl - intravenös"
// TODO: Spec has a blank space too much, thats why this was missing previously - not reported to divi unitl now, please check later
* #3103io "Gelatine - intraossär"
* #3103iv "Gelatine - intravenös"
* #3197xx "vorbehandelt mit Kolloid - sämtliche Applikationsformen"
* #3198io "sonstige spezielle Infusion - intraossär"
* #3198iv "sonstige spezielle Infusion - intravenös"
* #999999 "kein Medikament / keine Infusion"
